"use client";

import { motion } from "framer-motion";
import { Link, Mail, QrCode, FileText, BrainCircuit, ShieldAlert } from "lucide-react";

export default function Features() {
  const features = [
    {
      title: "URL Scanner",
      description: "Analyze links in real-time with zero-day ML models and aggregated threat intelligence feeds.",
      icon: <Link className="w-6 h-6 text-primary" />,
      delay: 0.1,
    },
    {
      title: "Email & SMS Scanner",
      description: "Extract and verify embedded links, sender reputation, and urgency-based phishing heuristics.",
      icon: <Mail className="w-6 h-6 text-primary" />,
      delay: 0.2,
    },
    {
      title: "QR Code Decryptor",
      description: "Safely decode and analyze QR payloads before they execute malicious commands on your device.",
      icon: <QrCode className="w-6 h-6 text-primary" />,
      delay: 0.3,
    },
    {
      title: "Visual OCR Scanning",
      description: "Extract hidden text from suspicious screenshots and images to bypass traditional filters.",
      icon: <FileText className="w-6 h-6 text-secondary" />,
      delay: 0.4,
    },
    {
      title: "AI Security Copilot",
      description: "Understand the 'why'. Get human-readable explanations of threats generated by Gemini.",
      icon: <BrainCircuit className="w-6 h-6 text-secondary" />,
      delay: 0.5,
    },
    {
      title: "Global Threat Intel",
      description: "Cross-reference payloads with VirusTotal, PhishTank, and WHOIS databases instantly.",
      icon: <ShieldAlert className="w-6 h-6 text-secondary" />,
      delay: 0.6,
    },
  ];

  return (
    <section id="features" className="py-24 relative">
      <div className="container mx-auto px-4 md:px-6 relative z-10">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <h2 className="text-3xl md:text-5xl font-bold mb-6">
            Multi-Modal <span className="text-gradient">Threat Detection</span>
          </h2>
          <p className="text-lg text-foreground/70">
            A comprehensive suite of tools designed to analyze, detect, and explain security threats across all communication channels.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((feature, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: feature.delay }}
              className="glass-panel p-6 hover:-translate-y-1 transition-all duration-300 group"
            >
              <div className="w-12 h-12 rounded-lg bg-white/5 flex items-center justify-center mb-6 border border-white/10 group-hover:border-primary/50 transition-colors">
                {feature.icon}
              </div>
              <h3 className="text-xl font-semibold mb-3">{feature.title}</h3>
              <p className="text-foreground/60 leading-relaxed">
                {feature.description}
              </p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
